### ISSUE TITLE
Utopia example has no solutions with OSeMOSYS_Pyomo

### ISSUE THREAD

**Issue by LosWochos76** [OSeMOSYS/OSeMOSYS_Pyomo#10]
The OSeMOSYS_Pyomo repository contains an example file UTOPIA_2015_08_27. Running this example results in no valid solution which is probably not what inital users would expect.

**Comment by bjesse** [comment]
Im still getting no valid solution

> # ==========================================================
> # = Solver Results                                         =
> # ==========================================================
> # ----------------------------------------------------------
> #   Problem Information
> # ----------------------------------------------------------
> Problem: 
> - Name: unknown
>   Lower bound: -inf
>   Upper bound: inf
>   Number of objectives: 1
>   Number of constraints: 301146
>   Number of variables: 296083
>   Number of nonzeros: 675005
>   Sense: minimize
> # ----------------------------------------------------------
> #   Solver Information
> # ----------------------------------------------------------
> Solver: 
> - Status: ok
>   Termination condition: other
>   Statistics: 
>     Branch and bound: 
>       Number of bounded subproblems: 0
>       Number of created subproblems: 0
>   Error rc: 0
>   Time: 4.584329605102539
